// flow-typed signature: 06d4a5937d984d73e40605bc48d01a5a
// flow-typed version: <<STUB>>/lintly_v0.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lintly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lintly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lintly/lib/config' {
  declare module.exports: any;
}

declare module 'lintly/lib/index' {
  declare module.exports: any;
}

declare module 'lintly/src/config' {
  declare module.exports: any;
}

declare module 'lintly/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lintly/lib/config.js' {
  declare module.exports: $Exports<'lintly/lib/config'>;
}
declare module 'lintly/lib/index.js' {
  declare module.exports: $Exports<'lintly/lib/index'>;
}
declare module 'lintly/src/config.js' {
  declare module.exports: $Exports<'lintly/src/config'>;
}
declare module 'lintly/src/index.js' {
  declare module.exports: $Exports<'lintly/src/index'>;
}
