version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run:
          name: "Install"
          command: "yarn global add bumpr@^2.7.2 && yarn install"
      - run:
          name: "Test"
          command: "bumpr check && yarn test"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
